steps:
# build the docker container
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/container-demo-gcp:latest', '.' ]
# push it to gcr
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/container-demo-gcp:latest' ]
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'hello-container',
         '--image', 'gcr.io/$PROJECT_ID/container-demo-gcp:latest',
         '--region', 'us-central1', '--platform', 'managed',
         '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/container-demo-gcp
